In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("istockphoto-182848692-612x612.jpg")

In [3]:
# Create a solid color test image
test_img = np.zeros((300, 400, 3), dtype=np.uint8)  # 400x300 black image
test_img[:] = (0, 255, 0)  # Make it green

cv2.imshow("Test Image", test_img)
cv2.waitKey(0)

-1

In [4]:
import os
print(os.path.exists("istockphoto-182848692-612x612.jpg"))  # Should return True

True


### For Displaying image in Google Colab

<p>cv2.imshow() is a disabled function in Colab because it can cause the Jupyter session to crash. Google Colab provides a specific function, cv2_imshow, for displaying images within the notebook.</p>

<code>from google.colab.patches import cv2_imshow 
cv2_imshow(test_img)</code>

In [5]:
cv2.imshow("window1",img)
cv2.waitKey(0) ## Induces an infinite delay, so that window never closes until the user does returning -1 

-1

In [6]:
print(img)

[[[  0   2   2]
  [  0   2   2]
  [  0   2   2]
  ...
  [ 21 135 255]
  [  7 144 255]
  [  0 136 255]]

 [[  0   2   2]
  [  0   2   2]
  [  0   2   2]
  ...
  [ 14 140 255]
  [  5 146 255]
  [  0 129 241]]

 [[  0   2   2]
  [  0   2   2]
  [  0   2   2]
  ...
  [  0 123 235]
  [  0 122 211]
  [  0  97 183]]

 ...

 [[156 128  93]
  [156 128  93]
  [157 129  94]
  ...
  [ 41  51  58]
  [ 42  52  59]
  [ 43  53  60]]

 [[150 122  87]
  [149 121  86]
  [150 122  87]
  ...
  [ 43  52  62]
  [ 44  53  63]
  [ 45  54  64]]

 [[141 117  81]
  [140 116  80]
  [141 117  81]
  ...
  [ 43  50  67]
  [ 45  52  69]
  [ 47  54  71]]]


In [7]:
print(type(img))

<class 'numpy.ndarray'>


In [8]:
print(img.shape)

(407, 612, 3)


### How to convert into grayscale

- cv2.cvtColor(): This function from the OpenCV library is used to convert images from one color space to another.
</br></br>
- img: This is the input image, typically loaded using cv2.imread(). By default, OpenCV reads images in BGR (Blue, Green, Red) format.
</br></br>
- cv2.COLOR_BGR2GRAY: This is a flag that tells OpenCV to convert the image from BGR color space to Grayscale. In Grayscale images, each pixel represents intensity, ranging from black (0) to white (255).
</br></br>
- grayscale: This is the resulting image after conversion. It's a single-channel image where each pixel denotes the intensity of light.
</br></br>

In [9]:
grayscale = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [10]:
cv2.imshow("grayscale_window",grayscale)
cv2.waitKey(0)

-1

- Unlike, previous, we have have only one channel, instead of three different channels for Red, Green and Blue. So, the third value from the tuple is ommitted out.

In [11]:
print(grayscale.shape)

(407, 612)


## **Playing with RGB Color Channels**

IMAGE[Dimension1,Dimension2,COLOR_CHANNEL]

<code> blue = image[:,:,0] </code></br>
<code> green = image[:,:,1] </code></br>
<code> red = image[:,:,2] </code></br>

### **Making The Blue Component Zero**

• The code removes the blue component from a 3D numpy array representing an image

• The resulting image has only green and red channels, leading to a yellowish shade

In [13]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Making the Blue component to zero
flowers[:,:,0]=0
cv2.imshow("zero_blue",flowers)
cv2.waitKey(0)

-1

### **Making The Green Component Zero**

• The code removes the green component from a 3D numpy array representing an image

• The resulting image has only blue and red channels, leading to a purple shade

In [15]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Making the Green component to zero
flowers[:,:,1]=0
cv2.imshow("zero_green",flowers)
cv2.waitKey(0)

-1

### **Making The Red Component Zero**

• The code removes the red component from a 3D numpy array representing an image

• The resulting image has only green and blue channels in the image

In [16]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Making the Red component to zero
flowers[:,:,2]=0
cv2.imshow("zero_red",flowers)
cv2.waitKey(0)

-1

### **Showing The Red Component only**

• The code displays the red component from a 3D numpy array representing an image

• The resulting image has only red channels, making green and blue components = zero

In [17]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Red component
flowers[:,:,0]=0
flowers[:,:,1]=0
cv2.imshow("only_red",flowers)
cv2.waitKey(0)

-1

### **Showing The Blue Component only**

• The code displays the blue component from a 3D numpy array representing an image

• The resulting image has only blue channels, making green and red components = zero

In [18]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Blue component
flowers[:,:,1]=0
flowers[:,:,2]=0
cv2.imshow("only_blue",flowers)
cv2.waitKey(0)

-1

### **Showing The Green Component only**

• The code displays the green component from a 3D numpy array representing an image

• The resulting image has only green channels, making red and blue components = zero

In [19]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Green component
flowers[:,:,0]=0
flowers[:,:,2]=0
cv2.imshow("only_green",flowers)
cv2.waitKey(0)

-1

In [20]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Maximum Blue Component
flowers[:,:,0]=255
cv2.imshow("Max_blue",flowers)
cv2.waitKey(0)

-1

In [21]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Maximum Green Component
flowers[:,:,1]=255
cv2.imshow("Max_green",flowers)
cv2.waitKey(0)

-1

In [26]:
flowers = cv2.imread("istockphoto-182848692-612x612.jpg")
## Maximum Green Component
flowers[:,:,2]=255
cv2.imshow("Max_red",flowers)
cv2.waitKey(0)

-1

### **How To Stack Images**

In [23]:
imgRed = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Red Component
imgBlue = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Blue Component
imgGreen = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Green Component
## Making the Blue and Green component to zero
imgRed[:,:,0]=0
imgRed[:,:,1]=0
## Making the Red and Green component to zero
imgBlue[:,:,1]=0
imgBlue[:,:,2]=0
## Making the Red and Blue component to zero
imgGreen[:,:,0]=0
imgGreen[:,:,2]=0
new_img = np.hstack((imgBlue,imgRed,imgGreen))
cv2.imshow("New Image",new_img)
cv2.waitKey(0)

-1

In [24]:
imgwithoutRed = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Red Component
imgwithoutblue = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Blue Component
imgwithoutgreen = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Green Component
## Making the Blue component to zero
imgwithoutblue[:,:,0]=0
## Making the Green component to zero
imgwithoutgreen[:,:,1]=0
## Making the Red component to zero
imgwithoutRed[:,:,2]=0
new_img = np.hstack((imgwithoutblue,imgwithoutgreen,imgwithoutRed))
cv2.imshow("New Image",new_img)
cv2.waitKey(0)

-1

In [25]:
imgmaxRed = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Red Component
imgmaxblue = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Blue Component
imgmaxgreen = cv2.imread("istockphoto-182848692-612x612.jpg") ## For displaying Green Component
## Making the Blue component to zero
imgmaxblue[:,:,0]=255
## Making the Green component to zero
imgmaxgreen[:,:,1]=255
## Making the Red component to zero
imgmaxRed[:,:,2]=255
new_img = np.hstack((imgmaxblue,imgmaxgreen,imgmaxRed))
cv2.imshow("New Image",new_img)
cv2.waitKey(0)

-1

### Image Resize
- <code> cv2.resize(img,dimension_tuple(256,256,3)) </code>

In [31]:
## Image Resize
img_resize = cv2.resize(img,(256,256))
## Display the image
cv2.imshow("Image Resized",img_resize)
cv2.waitKey(0)

-1

In [32]:
print(img_resize.shape)

(256, 256, 3)


In [34]:
## Image Resize
img_resize_to_half = cv2.resize(img,(img.shape[1]//2,img.shape[0]//2))
## OpenCV takes second index dimension of its shape first followed by the first so img.shape[1] first followed by img.shape[0]
## Display the image
cv2.imshow("Half Resized Image",img_resize_to_half)
cv2.waitKey(0)

-1

### Flipping an Image

- <code>cv2.flip(Image,flip_code) #flip_code = {0,1,-1}</code>
</br></br>
- Flipping is used in Data Augmentation and creating new datasets for the data

In [35]:
img_flip = cv2.flip(img,0) #Verical flip
img_stack = np.hstack((img,img_flip))
cv2.imshow("Flipped Image",img_stack)
cv2.waitKey(0)

-1

In [38]:
img_flip = cv2.flip(img,1) #Horizontal flip
img_stack = np.vstack((img,img_flip))
cv2.imshow("Flipped Image",img_stack)
cv2.waitKey(0)

-1

In [39]:
img_flip = cv2.flip(img,-1) #Horizontal + Verical flip
img_stack = np.vstack((img,img_flip))
cv2.imshow("Flipped Image",img_stack)
cv2.waitKey(0)

-1

### Cropping An Image

In [40]:
img_crop = img[100:300,200:500]
cv2.imshow("Cropped Image",img_crop)
cv2.waitKey(0)

-1

### Saving An Image

- <Code>cv2.imwrite("{{Name of the file to be saved}}",image)</Code>

In [41]:
cv2.imwrite("Flowers.jpg",img)

True

In [42]:
img_flip_1 = cv2.flip(img,1) #Horizontal flip
img_stack_1 = np.hstack((img,img_flip_1))
img_flip_2 = cv2.flip(img,0) #Verical flip
img_flip_3 = cv2.flip(img,-1) #Horizontal + Verical flip
img_stack_2 = np.hstack((img_flip_2,img_flip_3))
img_stack = np.vstack((img_stack_1,img_stack_2))
cv2.imwrite("Flowers_mirror.jpg",img_stack)

True